import type { Product } from "./product";

export const products: Product[] = [
  {
    name: "Wireless Headphones",
    img: "https://picsum.photos/id/180/400/400",
    seller: "marcorey",
    category: "Electronics",
    stocks: 120,
    description: "High quality wireless headphones with noise cancellation.",
    rating: 5,
    price: 99.99,
  },
  {
    name: "Organic Almonds",
    img: "https://picsum.photos/id/1080/400/400",
    seller: "jlee_shop",
    category: "Food",
    stocks: 300,
    description: "Raw and organic almonds sourced from local farms.",
    rating: 4,
    price: 15.5,
  },
  {
    name: "Building Blocks Set",
    img: "https://picsum.photos/id/1076/400/400",
    seller: "marcorey",
    category: "Toys",
    stocks: 50,
    description: "Colorful building blocks to stimulate creativity in kids.",
    rating: 4,
    price: 25.0,
  },
  {
    name: "Men's Casual T‑Shirt",
    img: "https://picsum.photos/id/659/400/400",
    seller: "jlee_shop",
    category: "Clothing",
    stocks: 200,
    description: "Comfortable cotton T‑shirt available in multiple colors.",
    rating: 3,
    price: 19.99,
  },
  {
    name: "Smartphone 5G",
    img: "https://picsum.photos/id/1/400/400",
    seller: "marcorey",
    category: "Electronics",
    stocks: 75,
    description: "Latest generation 5G smartphone with high‑res camera.",
    rating: 5,
    price: 699.0,
  },
  {
    name: "Granola Mix",
    img: "https://picsum.photos/id/292/400/400",
    seller: "jlee_shop",
    category: "Food",
    stocks: 180,
    description: "Crunchy and tasty granola made with natural ingredients.",
    rating: 4,
    price: 7.99,
  },
  {
    name: "Remote Control Car",
    img: "https://picsum.photos/id/1084/400/400",
    seller: "marcorey",
    category: "Toys",
    stocks: 90,
    description: "Fast and durable RC car for kids aged 6 and up.",
    rating: 5,
    price: 39.99,
  },
  {
    name: "Women's Jeans",
    img: "https://picsum.photos/id/1011/400/400",
    seller: "jlee_shop",
    category: "Clothing",
    stocks: 150,
    description: "Slim‑fit jeans with comfortable stretch fabric.",
    rating: 4,
    price: 49.99,
  },
  {
    name: "Bluetooth Speaker",
    img: "https://picsum.photos/id/1081/400/400",
    seller: "marcorey",
    category: "Electronics",
    stocks: 110,
    description:
      "Portable Bluetooth speaker with rich bass and long battery life.",
    rating: 4,
    price: 59.99,
  },
  {
    name: "Organic Honey",
    img: "https://picsum.photos/id/1040/400/400",
    seller: "jlee_shop",
    category: "Food",
    stocks: 220,
    description: "Pure organic honey harvested from wildflowers.",
    rating: 5,
    price: 12.5,
  },
];
